name: Firebase Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Install Angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node: 16
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Installing dependencies
        working-directory: frontend/angular/xpose
        run: npm install
      
      - name: Building Project
        working-directory: frontend/angular/xpose
        run: npm run build

      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
