name: build

on:
  push:
    branches:
      - '*'
    paths:
      - 'backend/event-posts-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Install dependencies for event posts service
        working-directory: backend/event-posts-service/
        run: npm install

      # - name: Run tests for event posts service
      #   working-directory: backend/event-posts-service/
      #   run: npm test
