name: build

on:
  push:
    branches:
      - '*'
    paths:
      - 'backend/events-service/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Install dependencies for events service
        working-directory: backend/events-service
        run: npm install

      - name: Run tests for event chats service
        working-directory: backend/events-service/
        run: npm test
