name: build

on:
  push:
    branches:
      - '*'
    paths:
      - 'backend/gateway-service/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Install dependencies for gateway service
        working-directory: backend/gateway-service/
        run: npm install

#       - name: Run tests for gateway service
#         working-directory: backend/gateway-service/
#         run: npm test
